### Application Level Image CI - Bookstack
### Dave Conroy <tiredofit@github>

name: 'Multi PHP Version Build'
on:
  push:
    paths:
    - '**'
    - '!README.md'
jobs:
#  php80:
#    uses: tiredofit/github_actions/.github/workflows/php80_alpine_amd64_armv7_arm64.yml@main
#    secrets: inherit
#  php81:
#    uses: tiredofit/github_actions/.github/workflows/php81_alpine_amd64_armv7_arm64.yml@main
#    secrets: inherit
  php82:
    uses: tiredofit/github_actions/.github/workflows/php82_alpine_amd64.yml@main
    secrets: inherit
